# Generated by Django 5.2.9 on 2025-12-21 07:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='header_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
