# Generated by Django 5.2.9 on 2025-12-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_achievementcomment_achievementlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='reflection',
            field=models.TextField(blank=True),
        ),
    ]
