# Generated by Django 5.2.9 on 2025-12-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_dailyentry_reflection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='descriptions',
        ),
    ]
