# Generated by Django 5.2.9 on 2026-01-20 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_help_help_comment_help_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='help_comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='help',
            name='category',
            field=models.CharField(default='ok', max_length=100),
        ),
        migrations.AlterField(
            model_name='help_comment',
            name='help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracker.help'),
        ),
        migrations.AlterField(
            model_name='help_comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='help_like',
            name='help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tracker.help'),
        ),
    ]
