# Generated by Django 5.2.6 on 2026-02-28 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_help_options_alter_help_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Delete models first to avoid field reference issues
        migrations.DeleteModel(
            name='AchievementComment',
        ),
        migrations.DeleteModel(
            name='AchievementLike',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Help_comment',
        ),
        migrations.DeleteModel(
            name='Help_like',
        ),
        migrations.DeleteModel(
            name='Help',
        ),
        # Now modify DailyEntry
        migrations.RemoveField(
            model_name='dailyentry',
            name='ratings',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='cn_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='dbms_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='dsa_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='os_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='system_design_description',
            field=models.TextField(blank=True),
        ),
        # Create new models
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=200)),
                ('questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='tracker.dailyentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('score', models.FloatField()),
                ('passed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tracker.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
